<a href="https://colab.research.google.com/github/ozdemirdemiroz/kendi-kendine/blob/main/numpy%20temel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np
arr_1D=np.array([2,4,6,8,10]) #1D array
print(arr_1D)

arr_1D_arrange= np.arange(10,50,5) #1D array arange kullanarak, (başlangıç , bitiş , kaçar kaçar)
print(arr_1D_arrange)

arr_1D_linspace_1=np.linspace(0,100,11) #1D array linspace kullanarak , eşit aralıkla böler (başlangıç ,bitiş ,kaç parca)
print(arr_1D_linspace_1)
arr_1D_linspace_2=np.linspace(0,10,4)
print(arr_1D_linspace_2)

arr_2D_1=np.arange(0,10,4)
arr_2D_2=np.arange(0,20,8)
arr_2D=np.vstack((arr_2D_1,arr_2D_2)) #2 tane 1D array oluşturup , vstack ile alt alta birleştirdik.
print(arr_2D)

dosya=open("arr_deneme","wb") #kaydetmek için yazma modunda bir dosya oluşturduk 
np.save(dosya,arr_2D)
dosya.close

dosya_2= open ("arr_deneme","rb") #dosyayı geri çağırmak için 
arr=np.load(dosya_2)
print(arr)

[ 2  4  6  8 10]
[10 15 20 25 30 35 40 45]
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[ 0.          3.33333333  6.66666667 10.        ]
[[ 0  4  8]
 [ 0  8 16]]
[[ 0  4  8]
 [ 0  8 16]]


In [31]:
zeros=np.zeros((3,4),dtype=int) #sıfırlardan bir matris oluşturma , normalde data tipi float , int olarak değiştirdik 
print(zeros)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [32]:
zeros[0,1]=5  #matrisin ilk satırının ikinci elemanını 5 olarak değiştiridik 
print(zeros)

[[0 5 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [34]:
birler=np.ones((2,2))
print(birler)

[[1. 1.]
 [1. 1.]]


In [39]:
satir=zeros[0,:] #belirli bir satırı stünü veya elemanı seçmek . array[satır , stun ]
print(satir)

[0 5 0 0]


In [41]:
for x in np.nditer(arr_2D):  #array içinde iterasyon 
  print(x,end=' ')   # end=' ' yazınca yan yana yazıyor
  

0 4 8 0 8 16 